### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Rexogamer**
I fixed some grammatical errors.

### CODE REVIEW

**Comment by nlogozzo** [comment]
Thank you. These changes will be made in the next version of NDOS

**Comment by Rexogamer** [comment]
It mildly annoys me how you close PRs _you will use_ and say that the changes will be “in the next version.” Just keep the PR open, save yourself some time and merge the commits in when you’re ready to merge them. Or are you too vain to let anyone else’s work touch your pwecious bowt?

**Comment by nlogozzo** [comment]
I don't have the git repo synced on my pc. Meaning once I merge the
changes, after I upload a new version did changes will just get overwritten
and you will never see those changes

**Comment by Rexogamer** [comment]
well then set up sync, or just do it on pc only

**Comment by nlogozzo** [comment]
1. I am on PC only
2. It's not easy to just set up an existing project with git especially
when I'm already using a cloud service like OneDrive to save the project

**Comment by Rexogamer** [comment]
I see... just seems a bit odd to close a PR if you intend to basically but not actually merge it.

**Comment by nlogozzo** [comment]
I'm sorry but as I said before even if I merge it, it will get overrided
when I upload the next version

**Comment by Rexogamer** [comment]
ik

**Comment by nlogozzo** [comment]
Tux V7.5.2 has been released with your changes included

**Pull request closed without merging**
